export function localImages() {
  return {
    logo: require("../images/logo.png"),
    default_avatar: require("../images/default_avatar.jpg"),
    ic_google: require("../images/ic_google.png"),
    ic_facebook: require("../images/ic_facebook.png"),
    ic_home: require("../images/ic_home.png"),
    ic_home_fill: require("../images/ic_home_fill.png"),
    ic_shopping_cart: require("../images/ic_shopping_cart.png"),
    ic_shopping_cart_fill: require("../images/ic_shopping_cart_fill.png"),
    ic_window: require("../images/ic_window.png"),
    ic_window_fill: require("../images/ic_window_fill.png"),
    ic_profile: require("../images/ic_profile.png"),
    ic_profile_fill: require("../images/ic_profile_fill.png"),
    ic_mac: require("../mac.png"),
    ic_plus: require("../images/ic_plus.png"),
    ic_minus: require("../images/ic_minus.png"),
    ic_cooling: require("../images/ic_cooling.jpg"),
    ic_cpu: require("../images/ic_cpu.png"),
    ic_case: require("../images/ic_case.jpg"),
    ic_gpu: require("../images/ic_gpu.png"),
    ic_mainboard: require("../images/ic_mainboard.jpg"),
    ic_power: require("../images/ic_mainboard.jpg"),
    ic_storage: require("../images/ic_storage.png"),
    ic_ram: require("../images/ic_ram.png"),
    ic_home_red: require("../images/ic_home_red.png"),
    ic_vnpay: require("../images/ic_vnpay.webp"),
  };
}
